services:
    db:
      image: postgres
      restart: always
      container_name: postgres_for_metabase
      environment:
        - POSTGRES_PASSWORD=PASWORD
        - POSTGRES_USER=USERNAME
        - POSTGRES_DB=DATABASE
      ports:
        - 25432:5432
      volumes:
        - ./db-data:/var/lib/postgresql/data
      networks:
        - postgres-network
    metabase:
      container_name: metabase
      volumes:
        - ./metabase-data:/metabase-data
      environment:
        - MB_DB_TYPE=postgres
        - MB_DB_DBNAME=DATABASE
        - MB_DB_PORT=5432
        - MB_DB_USER=USERNAME
        - MB_DB_PASS=PASWORD
        - MB_DB_HOST=db
      ports:
        - 3010:3000
      image: metabase/metabase
      restart: always
      depends_on:
        - db
      networks:
        - postgres-network
networks:
  postgres-network:
    driver: bridge